# TODO: setup so debug works too: https://code.visualstudio.com/docs/containers/debug-common (otherwise, just debug from the host machine works fine)
version: '3'

services:
  application:
    image: nikolaik/python-nodejs:python3.8-nodejs13
    volumes: 
      - .:/app
    ports:
      - "5005:5005"
      - "5006:5006"
    command: bash -c "
        cd /app/axidraw_cli/AxiDraw_HTA_API_v254_r5 &&
        pip install . &&
        cd /app &&
        npm i && 
        npm start 
      "